version: '3'

services:
  rundeck:
    image: rundeck/rundeck:4.17.0
    ports:
      - "4440:4440"
    environment:
      - RUNDECK_GRAILS_URL=${RUNDECK_GRAILS_URL}
      - RUNDECK_SECURITY_SETUP=${RUNDECK_SECURITY_SETUP}
      - RUNDECK_DATABASE_DRIVER=${RUNDECK_DATABASE_DRIVER}
      - RUNDECK_DATABASE_USERNAME=${RUNDECK_DATABASE_USERNAME}
      - RUNDECK_DATABASE_PASSWORD=${RUNDECK_DATABASE_PASSWORD}
      - RUNDECK_DATABASE_URL=${RUNDECK_DATABASE_URL}
      - RUNDECK_DATABASE_TYPE=${RUNDECK_DATABASE_TYPE}
      - RUNDECK_LOGGING_STRATEGY=${RUNDECK_LOGGING_STRATEGY}
      - RUNDECK_SERVER_FORWARDED=${RUNDECK_SERVER_FORWARDED}
    volumes:
      - ./data:/home/rundeck/server/data
      - ./projects:/home/rundeck/projects
    depends_on:
      - postgres

  postgres:
    image: postgres:13.12-bullseye
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data