apiVersion: v1
kind: PersistentVolume
metadata:
  name: rundeck-data-pv
  namespace: default
  labels:
    app: rundeck
    type: data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: <nome-do-storage-class>
  hostPath:
    path: /path/to/host/rundeck-data