apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-data-pvc
  namespace: default
  labels:
    app: rundeck
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <nome-do-storage-class>
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: rundeck
      type: data