version: '3'

services:
  rundeck:
    image: rundeck/rundeck:4.17.0
    ports:
      - "4440:4440"
    environment:
      - RUNDECK_GRAILS_URL=${RUNDECK_GRAILS_URL}
      - RUNDECK_SECURITY_SETUP=${RUNDECK_SECURITY_SETUP}
      - RUNDECK_API_TOKENS_DURATION_MAX=${RUNDECK_API_TOKENS_DURATION_MAX}
      - RUNDECK_DATABASE_DRIVER=${RUNDECK_DATABASE_DRIVER}
      - RUNDECK_DATABASE_USERNAME=${RUNDECK_DATABASE_USERNAME}
      - RUNDECK_DATABASE_PASSWORD=${RUNDECK_DATABASE_PASSWORD}
      - RUNDECK_DATABASE_URL=${RUNDECK_DATABASE_URL}
      - RUNDECK_LOGGING_STRATEGY=${RUNDECK_LOGGING_STRATEGY}
      - RUNDECK_SERVER_FORWARDED=${RUNDECK_SERVER_FORWARDED}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
